### ISSUE TITLE
Bridge crashes with unhandled exception

### ISSUE THREAD

**Issue by wolfpld** [matrix-discord/mx-puppet-discord#104]
```
Oct-27 11:59:15.479 [bot-sdk-MatrixLiteClient] error: (REQ-99) {"errcode":"M_UNKNOWN","error":"This room has been blocked on this server"}
Oct-27 11:59:15.479 [UserSync] error: Error setting room overrides for 288411937962721305 in 585217639891075255: {
  errcode: 'M_UNKNOWN',
  error: 'This room has been blocked on this server'
}
Oct-27 11:59:15.480 [bot-sdk-MatrixLiteClient] error: (REQ-100) {"errcode":"M_UNKNOWN","error":"This room has been blocked on this server"}
Oct-27 11:59:15.480 [UserSync] error: Error setting room overrides for 288411937962721305 in 675322971182858260: {
  errcode: 'M_UNKNOWN',
  error: 'This room has been blocked on this server'
}
[more such errors]
Oct-27 11:59:15.482 [bot-sdk-MatrixLiteClient] error: (REQ-101) {"errcode":"M_UNKNOWN","error":"This room has been blocked on this server"}
Oct-27 11:59:15.485 [bot-sdk-MatrixLiteClient] error: (REQ-102) {"errcode":"M_UNKNOWN","error":"This room has been blocked on this server"}
[more such errors]
node:internal/process/promises:218
          triggerUncaughtException(err, true /* fromPromise */);
          ^
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<IncomingMessage>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mx-puppet-discord@0.0.0 start: `npm run-script build && node ./build/index.js`
npm ERR! Exit status 1
```

Stack trace from debug log:

```
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (node:events:327:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (node:events:327:20)
13 verbose stack     at maybeClose (node:internal/child_process:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
```

**Comment by Sorunome** [comment]
Never saw

> This room has been blocked on this server

yet. What did you try to do which triggered this?

**Comment by wolfpld** [comment]
To be honest, I don't know. Maybe I joined some guilds and then left them? Matrix is horribly opaque when it comes to maintaining the server. While this error is the cause of the issue, solving it is not needed to fix the problem for me, as the error itself is not affecting my usage. Looking back in the logs I think I can see what's happening more clearly.

```
Oct-18 13:45:36.886 [bot-sdk-MatrixLiteClient] error: (REQ-5) {"errcode":"M_UNKNOWN","error":"This room has been blocked on this server"}
(node:604) UnhandledPromiseRejectionWarning: #<IncomingMessage>
(Use `node --trace-warnings ...` to show where the warning was created)
(node:604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:604) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It would seem that after a recent upgrade of nodejs this deprecation warning become an error.
