### ISSUE TITLE
SyntaxError: Unexpected token on Startup

### ISSUE THREAD

**Issue by mirdaki** [matrix-discord/mx-puppet-discord#134]
Hello, on startup, I run into a SyntaxError exception. Afterwards, any message to Discord will fail and log a "No relay found". Messages from Discord don't seem to trigger logs. I did comment on a similar issue (#73) about the relay, but felt the SyntaxError should get it's own.

```
Mar 28 18:57:08 redacted systemd[1]: Stopped Matrix Mx Puppet Discord bridge.
Mar 28 19:11:44 redacted systemd[1]: Starting Matrix Mx Puppet Discord bridge...
Mar 28 19:11:49 redacted systemd[1]: Started Matrix Mx Puppet Discord bridge.
Mar 28 19:11:58 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:11:58.971 [Store] info: Starting DB Init
Mar 28 19:11:58 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:11:58.979 [Store] info: connString present in config, using postgres
Mar 28 19:11:58 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:11:58.991 [Postgres] info: Opening @matrix-postgres:5432/matrix_mx_puppet_discord?sslmode=disable
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:11:59.620 [Store] info: Database schema version is 16, latest version is 16
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:11:59.639 [Store] info: Starting DB Init
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:11:59.650 [Store] info: Database schema version is 4, latest version is 4
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:11:59.653 [PuppetBridge] info: Starting application service....
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:11:59.672 [bot-sdk-MatrixLiteClient] info: (REQ-1) POST http://matrix-nginx-proxy:12080/_matrix/client/r0/register
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:11:59.756 [bot-sdk-MatrixLiteClient] error: (REQ-1) <html>
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]: <head><title>502 Bad Gateway</title></head>
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]: <body>
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]: <center><h1>502 Bad Gateway</h1></center>
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]: <hr><center>nginx</center>
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]: </body>
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]: </html>
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:11:59.760 [PuppetBridge] error: Unhandled Promise Rejection: SyntaxError: Unexpected token < in JSON at position 0
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]:     at JSON.parse (<anonymous>)
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]:     at Intent.<anonymous> (/opt/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Intent.js:194:41)
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]:     at Generator.throw (<anonymous>)
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]:     at rejected (/opt/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Intent.js:15:65)
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]:     at processTicksAndRejections (node:internal/process/task_queues:94:5)
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:11:59.772 [PuppetBridge] error: Promise {
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]:   <rejected> SyntaxError: Unexpected token < in JSON at position 0
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]:       at JSON.parse (<anonymous>)
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]:       at Intent.<anonymous> (/opt/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Intent.js:194:41)
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]:       at Generator.throw (<anonymous>)
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]:       at rejected (/opt/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Intent.js:15:65)
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]:       at processTicksAndRejections (node:internal/process/task_queues:94:5)
Mar 28 19:11:59 redacted matrix-mx-puppet-discord[170458]: }
Mar 28 19:12:07 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:12:07.112 [bot-sdk-Appservice] info: Processing transaction 1064
Mar 28 19:12:07 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:12:07.122 [bot-sdk-Appservice] info: Processing ephemeral event of type m.presence
Mar 28 19:12:07 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:12:07.127 [MatrixEventHandler] info: Got presence event for mxid @redacted-my-user
Mar 28 19:12:07 redacted matrix-mx-puppet-discord[170458]: 172.18.0.7 - - [29/Mar/2021:02:12:07 +0000] "PUT /transactions/1064?access_token=redacted-token HTTP/1.1" 200 2 "-" "Synapse/1.30.1"
Mar 28 19:12:54 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:12:54.068 [bot-sdk-Appservice] info: Processing transaction 1065
Mar 28 19:12:54 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:12:54.070 [bot-sdk-Appservice] info: Processing ephemeral event of type m.receipt
Mar 28 19:12:54 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:12:54.071 [MatrixEventHandler] info: Got receipt event in room !redacted-room
Mar 28 19:12:54 redacted matrix-mx-puppet-discord[170458]: 172.18.0.7 - - [29/Mar/2021:02:12:54 +0000] "PUT /transactions/1065?access_token=redacted-token HTTP/1.1" 200 2 "-" "Synapse/1.30.1"
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.397 [bot-sdk-Appservice] info: Processing transaction 1066
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.398 [bot-sdk-Appservice] info: Processing ephemeral event of type m.presence
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.398 [MatrixEventHandler] info: Got presence event for mxid @redacted-my-user
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: 172.18.0.7 - - [29/Mar/2021:02:14:10 +0000] "PUT /transactions/1066?access_token=redacted-token HTTP/1.1" 200 2 "-" "Synapse/1.30.1"
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.431 [bot-sdk-Appservice] info: Processing transaction 1067
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.432 [bot-sdk-Appservice] info: Processing ephemeral event of type m.presence
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.432 [MatrixEventHandler] info: Got presence event for mxid @redacted-user
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.433 [bot-sdk-Appservice] info: Processing ephemeral event of type m.presence
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.434 [MatrixEventHandler] info: Got presence event for mxid @redacted-my-user
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.438 [bot-sdk-Appservice] info: Processing ephemeral event of type m.presence
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.439 [MatrixEventHandler] info: Got presence event for mxid @redacted-user
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.439 [bot-sdk-Appservice] info: Processing ephemeral event of type m.presence
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.440 [MatrixEventHandler] info: Got presence event for mxid @redacted-user
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.440 [bot-sdk-Appservice] info: Processing ephemeral event of type m.presence
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.441 [MatrixEventHandler] info: Got presence event for mxid @redacted-user
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.442 [bot-sdk-Appservice] info: Processing ephemeral event of type m.presence
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.442 [MatrixEventHandler] info: Got presence event for mxid @redacted-user
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.443 [bot-sdk-Appservice] info: Processing ephemeral event of type m.presence
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.444 [MatrixEventHandler] info: Got presence event for mxid @redacted-user
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.444 [bot-sdk-Appservice] info: Processing ephemeral event of type m.presence
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.445 [MatrixEventHandler] info: Got presence event for mxid @redacted-user
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.445 [bot-sdk-Appservice] info: Processing ephemeral event of type m.presence
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.447 [MatrixEventHandler] info: Got presence event for mxid @redacted-user
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.448 [bot-sdk-Appservice] info: Processing ephemeral event of type m.presence
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.448 [MatrixEventHandler] info: Got presence event for mxid @redacted-user
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.449 [bot-sdk-Appservice] info: Processing ephemeral event of type m.presence
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.450 [MatrixEventHandler] info: Got presence event for mxid @redacted-user
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.452 [bot-sdk-Appservice] info: Processing ephemeral event of type m.presence
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.453 [MatrixEventHandler] info: Got presence event for mxid @redacted-user
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.454 [bot-sdk-Appservice] info: Processing ephemeral event of type m.presence
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.456 [MatrixEventHandler] info: Got presence event for mxid @redacted-user
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.457 [bot-sdk-Appservice] info: Processing ephemeral event of type m.presence
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.459 [MatrixEventHandler] info: Got presence event for mxid @redacted-user
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.460 [bot-sdk-Appservice] info: Processing ephemeral event of type m.presence
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.461 [MatrixEventHandler] info: Got presence event for mxid @redacted-user
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.467 [bot-sdk-Appservice] info: Processing ephemeral event of type m.presence
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.470 [MatrixEventHandler] info: Got presence event for mxid @redacted-user
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.471 [bot-sdk-Appservice] info: Processing ephemeral event of type m.presence
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.474 [MatrixEventHandler] info: Got presence event for mxid @redacted-user
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.475 [bot-sdk-Appservice] info: Processing ephemeral event of type m.presence
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.476 [MatrixEventHandler] info: Got presence event for mxid @redacted-user
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.476 [bot-sdk-Appservice] info: Processing ephemeral event of type m.presence
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.477 [MatrixEventHandler] info: Got presence event for mxid @redacted-user
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: 172.18.0.7 - - [29/Mar/2021:02:14:10 +0000] "PUT /transactions/1067?access_token=redacted-token HTTP/1.1" 200 2 "-" "Synapse/1.30.1"
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.549 [MatrixEventHandler] error: Puppet not found. Something is REALLY wrong!!!!
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.552 [MatrixEventHandler] error: Puppet not found. Something is REALLY wrong!!!!
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.556 [MatrixEventHandler] error: Puppet not found. Something is REALLY wrong!!!!
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.569 [MatrixEventHandler] error: Puppet not found. Something is REALLY wrong!!!!
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.574 [MatrixEventHandler] error: Puppet not found. Something is REALLY wrong!!!!
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.578 [MatrixEventHandler] error: Puppet not found. Something is REALLY wrong!!!!
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.591 [MatrixEventHandler] error: Puppet not found. Something is REALLY wrong!!!!
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.599 [MatrixEventHandler] error: Puppet not found. Something is REALLY wrong!!!!
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.601 [MatrixEventHandler] error: Puppet not found. Something is REALLY wrong!!!!
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.606 [MatrixEventHandler] error: Puppet not found. Something is REALLY wrong!!!!
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.617 [MatrixEventHandler] error: Puppet not found. Something is REALLY wrong!!!!
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.623 [MatrixEventHandler] error: Puppet not found. Something is REALLY wrong!!!!
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.625 [MatrixEventHandler] error: Puppet not found. Something is REALLY wrong!!!!
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.626 [MatrixEventHandler] error: Puppet not found. Something is REALLY wrong!!!!
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.629 [MatrixEventHandler] error: Puppet not found. Something is REALLY wrong!!!!
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.634 [MatrixEventHandler] error: Puppet not found. Something is REALLY wrong!!!!
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.640 [MatrixEventHandler] error: Puppet not found. Something is REALLY wrong!!!!
Mar 28 19:14:10 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:14:10.644 [MatrixEventHandler] error: Puppet not found. Something is REALLY wrong!!!!
Mar 28 19:19:28 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:28.695 [bot-sdk-Appservice] info: Processing transaction 1068
Mar 28 19:19:28 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:28.696 [bot-sdk-Appservice] info: Processing ephemeral event of type m.typing
Mar 28 19:19:28 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:28.697 [MatrixEventHandler] info: Got typing event in room redacted-room
Mar 28 19:19:28 redacted matrix-mx-puppet-discord[170458]: 172.18.0.7 - - [29/Mar/2021:02:19:28 +0000] "PUT /transactions/1068?access_token=redacted-token HTTP/1.1" 200 2 "-" "Synapse/1.30.1"
Mar 28 19:19:28 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:28.713 [MatrixEventHandler] error: Error handling appservice ephemeral.event Error: No relay found
Mar 28 19:19:28 redacted matrix-mx-puppet-discord[170458]:     at NamespaceHandler.<anonymous> (/opt/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:709:19)
Mar 28 19:19:28 redacted matrix-mx-puppet-discord[170458]:     at Generator.next (<anonymous>)
Mar 28 19:19:28 redacted matrix-mx-puppet-discord[170458]:     at fulfilled (/opt/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:17:58)
Mar 28 19:19:28 redacted matrix-mx-puppet-discord[170458]:     at processTicksAndRejections (node:internal/process/task_queues:94:5)
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:29.283 [bot-sdk-Appservice] info: Processing transaction 1069
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:29.284 [bot-sdk-Appservice] info: Processing ephemeral event of type m.typing
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:29.284 [MatrixEventHandler] info: Got typing event in room redacted-room
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:29.287 [MatrixEventHandler] error: Error handling appservice ephemeral.event Error: No relay found
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]:     at NamespaceHandler.<anonymous> (/opt/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:709:19)
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]:     at Generator.next (<anonymous>)
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]:     at fulfilled (/opt/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:17:58)
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]:     at processTicksAndRejections (node:internal/process/task_queues:94:5)
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: 172.18.0.7 - - [29/Mar/2021:02:19:29 +0000] "PUT /transactions/1069?access_token=redacted-token HTTP/1.1" 200 2 "-" "Synapse/1.30.1"
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:29.526 [bot-sdk-Appservice] info: Processing transaction 1070
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:29.528 [bot-sdk-Appservice] info: Processing event of type m.room.message
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: 172.18.0.7 - - [29/Mar/2021:02:19:29 +0000] "PUT /transactions/1070?access_token=redacted-token HTTP/1.1" 200 2 "-" "Synapse/1.30.1"
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:29.538 [BotProvisioner] info: Got message to process with arg=test
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:29.557 [bot-sdk-MatrixLiteClient] info: (REQ-2) PUT http://matrix-nginx-proxy:12080/_matrix/client/r0/rooms/redacted/send/m.room.message/1616984369557__REQ1
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:29.575 [bot-sdk-Appservice] info: Processing transaction 1071
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:29.576 [bot-sdk-Appservice] info: Processing event of type m.room.message
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:29.577 [bot-sdk-Appservice] info: Processing event of type m.room.message
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:29.579 [MatrixEventHandler] error: Error handling appservice room.event Error: No relay found
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]:     at NamespaceHandler.<anonymous> (/opt/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:709:19)
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]:     at Generator.next (<anonymous>)
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]:     at fulfilled (/opt/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:17:58)
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]:     at processTicksAndRejections (node:internal/process/task_queues:94:5)
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: 172.18.0.7 - - [29/Mar/2021:02:19:29 +0000] "PUT /transactions/1071?access_token=redacted-token HTTP/1.1" 200 2 "-" "Synapse/1.30.1"
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:29.585 [BotProvisioner] info: Got message to process with arg=help
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:29.591 [bot-sdk-MatrixLiteClient] info: (REQ-3) PUT http://matrix-nginx-proxy:12080/_matrix/client/r0/rooms/redacted/send/m.room.message/1616984369591__REQ2
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:29.751 [bot-sdk-Appservice] info: Processing transaction 1072
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:29.753 [bot-sdk-Appservice] info: Processing event of type m.room.message
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: 172.18.0.7 - - [29/Mar/2021:02:19:29 +0000] "PUT /transactions/1072?access_token=redacted-token HTTP/1.1" 200 2 "-" "Synapse/1.30.1"
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:29.808 [bot-sdk-Appservice] info: Processing transaction 1073
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:29.809 [bot-sdk-Appservice] info: Processing ephemeral event of type m.presence
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: 172.18.0.7 - - [29/Mar/2021:02:19:29 +0000] "PUT /transactions/1073?access_token=redacted-token HTTP/1.1" 200 2 "-" "Synapse/1.30.1"
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:29.862 [bot-sdk-Appservice] info: Processing transaction 1074
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: Mar-29 02:19:29.863 [bot-sdk-Appservice] info: Processing event of type m.room.message
Mar 28 19:19:29 redacted matrix-mx-puppet-discord[170458]: 172.18.0.7 - - [29/Mar/2021:02:19:29 +0000] "PUT /transactions/1074?access_token=redacted-token HTTP/1.1" 200 2 "-" "Synapse/1.30.1"

```

I am using matrix-docker-ansible-deploy and the latest Docker tag. Let me know if I can provide any more info!

**Comment by expipiplus1** [comment]
FWIW I've bumped into this too,


```
May 05 10:10:48 sen mx-puppet-discord[982]: May-5 10:10:48.444 [bot-sdk-Appservice] info: Processing transaction 88668
May 05 10:10:48 sen mx-puppet-discord[982]: May-5 10:10:48.445 [bot-sdk-Appservice] info: Processing ephemeral event of type m.receipt
May 05 10:10:48 sen mx-puppet-discord[982]: May-5 10:10:48.445 [MatrixEventHandler] info: Got receipt event in room !xxx:a.b
May 05 10:10:48 sen mx-puppet-discord[982]: 127.0.0.1 - - [05/May/2021:02:10:48 +0000] "PUT /transactions/88668?access_token=aaaaaa HTTP/1.1" 200 2 "-" "Synapse/1.32.2"
May 05 10:10:48 sen mx-puppet-discord[982]: May-5 10:10:48.457 [MatrixEventHandler] error: Error handling appservice ephemeral.event Error: No relay found
May 05 10:10:48 sen mx-puppet-discord[982]:     at NamespaceHandler.<anonymous> (/nix/store/7r6dg7gfcwvi9ckzg9llfvci70yj6hvi-node_mx-puppet-discord-0.0.0/lib/node_modules/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:709:19)
May 05 10:10:48 sen mx-puppet-discord[982]:     at Generator.next (<anonymous>)
May 05 10:10:48 sen mx-puppet-discord[982]:     at fulfilled (/nix/store/7r6dg7gfcwvi9ckzg9llfvci70yj6hvi-node_mx-puppet-discord-0.0.0/lib/node_modules/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:17:58)
May 05 10:10:48 sen mx-puppet-discord[982]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

**Comment by expipiplus1** [comment]
Is this a duplicate of https://github.com/matrix-discord/mx-puppet-discord/issues/117?

**Comment by mirdaki** [comment]
Possibly? I don't have any guilds bridged, but that error is definitely the same
