### ISSUE TITLE
The program should exit unsuccessfully when failing to initialize

### ISSUE THREAD

**Issue by expipiplus1** [matrix-discord/mx-puppet-discord#141]
For example here if fails to initialize properly because synapse is failing, or hasn't started. In the below log it continues in some zombie state until my watchdog for https://github.com/matrix-discord/mx-puppet-discord/issues/117 kills it. 

If it were to fail then systemd would engage the `OnFailed` policy and in my case restart it.

```
-- Boot 1073120d4d994ed189f5b96c0d74b39d --
May 09 04:43:27 sen systemd[1]: Starting mx-puppet-discord, a Discord puppeting bridge for Matrix....
May 09 04:43:27 sen systemd[1]: Started mx-puppet-discord, a Discord puppeting bridge for Matrix..
May 09 04:43:33 sen mx-puppet-discord[982]: May-9 04:43:33.523 [Store] info: Starting DB Init
May 09 04:43:33 sen mx-puppet-discord[982]: May-9 04:43:33.540 [Store] info: connString present in config, using postgres
May 09 04:43:33 sen mx-puppet-discord[982]: May-9 04:43:33.545 [Postgres] info: Opening @localhost/mx-puppet-discord?host=/run/postgresql
May 09 04:43:33 sen mx-puppet-discord[982]: May-9 04:43:33.640 [Store] info: Database schema version is 16, latest version is 16
May 09 04:43:33 sen mx-puppet-discord[982]: May-9 04:43:33.655 [Store] info: Starting DB Init
May 09 04:43:33 sen mx-puppet-discord[982]: May-9 04:43:33.664 [Store] info: Database schema version is 4, latest version is 4
May 09 04:43:33 sen mx-puppet-discord[982]: May-9 04:43:33.670 [PuppetBridge] info: Starting application service....
May 09 04:43:33 sen mx-puppet-discord[982]: May-9 04:43:33.705 [bot-sdk-MatrixLiteClient] info: (REQ-1) POST https://matrix.monoid.al/_matrix/client/r0/register
May 09 04:43:33 sen mx-puppet-discord[982]: May-9 04:43:33.874 [bot-sdk-MatrixLiteClient] error: (REQ-1) <html>
May 09 04:43:33 sen mx-puppet-discord[982]: <head><title>502 Bad Gateway</title></head>
May 09 04:43:33 sen mx-puppet-discord[982]: <body>
May 09 04:43:33 sen mx-puppet-discord[982]: <center><h1>502 Bad Gateway</h1></center>
May 09 04:43:33 sen mx-puppet-discord[982]: <hr><center>nginx</center>
May 09 04:43:33 sen mx-puppet-discord[982]: </body>
May 09 04:43:33 sen mx-puppet-discord[982]: </html>
May 09 04:43:33 sen mx-puppet-discord[982]: May-9 04:43:33.888 [PuppetBridge] error: Unhandled Promise Rejection: SyntaxError: Unexpected token < in JSON at position 0
May 09 04:43:33 sen mx-puppet-discord[982]:     at JSON.parse (<anonymous>)
May 09 04:43:33 sen mx-puppet-discord[982]:     at Intent.<anonymous> (/nix/store/m7ys7454qsvqsxjvfiqpy0sb42256qrp-node_mx-puppet-discord-0.0.0/lib/node_modules/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Intent.js:194:41)
May 09 04:43:33 sen mx-puppet-discord[982]:     at Generator.throw (<anonymous>)
May 09 04:43:33 sen mx-puppet-discord[982]:     at rejected (/nix/store/m7ys7454qsvqsxjvfiqpy0sb42256qrp-node_mx-puppet-discord-0.0.0/lib/node_modules/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Intent.js:15:65)
May 09 04:43:33 sen mx-puppet-discord[982]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 09 04:43:33 sen mx-puppet-discord[982]: May-9 04:43:33.892 [PuppetBridge] error: Promise {
May 09 04:43:33 sen mx-puppet-discord[982]:   <rejected> SyntaxError: Unexpected token < in JSON at position 0
May 09 04:43:33 sen mx-puppet-discord[982]:       at JSON.parse (<anonymous>)
May 09 04:43:33 sen mx-puppet-discord[982]:       at Intent.<anonymous> (/nix/store/m7ys7454qsvqsxjvfiqpy0sb42256qrp-node_mx-puppet-discord-0.0.0/lib/node_modules/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Intent.js:194:41)
May 09 04:43:33 sen mx-puppet-discord[982]:       at Generator.throw (<anonymous>)
May 09 04:43:33 sen mx-puppet-discord[982]:       at rejected (/nix/store/m7ys7454qsvqsxjvfiqpy0sb42256qrp-node_mx-puppet-discord-0.0.0/lib/node_modules/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Intent.js:15:65)
May 09 04:43:33 sen mx-puppet-discord[982]:       at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 09 04:43:33 sen mx-puppet-discord[982]: }
May 09 08:04:35 sen mx-puppet-discord[982]: May-9 08:04:35.154 [bot-sdk-Appservice] info: Processing transaction 104787
May 09 08:04:35 sen mx-puppet-discord[982]: May-9 08:04:35.156 [bot-sdk-Appservice] info: Processing ephemeral event of type m.receipt
May 09 08:04:35 sen mx-puppet-discord[982]: May-9 08:04:35.158 [MatrixEventHandler] info: Got receipt event in room !WUPinvICGLJFjKwpsl:monoid.al
May 09 08:04:35 sen mx-puppet-discord[982]: 127.0.0.1 - - [09/May/2021:00:04:35 +0000] "PUT /transactions/104787?access_token=e5d48172-92e9-4492-b0af-16d6de8caec1 HTTP/1.1" 200 2 "-" "Synapse/1.32.2"
May 09 08:04:35 sen mx-puppet-discord[982]: May-9 08:04:35.209 [MatrixEventHandler] error: Error handling appservice ephemeral.event Error: No relay found
May 09 08:04:35 sen mx-puppet-discord[982]:     at NamespaceHandler.<anonymous> (/nix/store/m7ys7454qsvqsxjvfiqpy0sb42256qrp-node_mx-puppet-discord-0.0.0/lib/node_modules/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:709:19)
May 09 08:04:35 sen mx-puppet-discord[982]:     at Generator.next (<anonymous>)
May 09 08:04:35 sen mx-puppet-discord[982]:     at fulfilled (/nix/store/m7ys7454qsvqsxjvfiqpy0sb42256qrp-node_mx-puppet-discord-0.0.0/lib/node_modules/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:17:58)
May 09 08:04:35 sen mx-puppet-discord[982]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 09 08:04:52 sen mx-puppet-discord[982]: May-9 08:04:52.219 [bot-sdk-Appservice] info: Processing transaction 104788
May 09 08:04:52 sen mx-puppet-discord[982]: May-9 08:04:52.221 [bot-sdk-Appservice] info: Processing ephemeral event of type m.typing
May 09 08:04:52 sen mx-puppet-discord[982]: May-9 08:04:52.222 [MatrixEventHandler] info: Got typing event in room !WUPinvICGLJFjKwpsl:monoid.al
May 09 08:04:52 sen mx-puppet-discord[982]: May-9 08:04:52.225 [MatrixEventHandler] error: Error handling appservice ephemeral.event Error: No relay found
May 09 08:04:52 sen mx-puppet-discord[982]:     at NamespaceHandler.<anonymous> (/nix/store/m7ys7454qsvqsxjvfiqpy0sb42256qrp-node_mx-puppet-discord-0.0.0/lib/node_modules/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:709:19)
May 09 08:04:52 sen mx-puppet-discord[982]:     at Generator.next (<anonymous>)
May 09 08:04:52 sen mx-puppet-discord[982]:     at fulfilled (/nix/store/m7ys7454qsvqsxjvfiqpy0sb42256qrp-node_mx-puppet-discord-0.0.0/lib/node_modules/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:17:58)
May 09 08:04:52 sen mx-puppet-discord[982]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 09 08:04:52 sen mx-puppet-discord[982]: 127.0.0.1 - - [09/May/2021:00:04:52 +0000] "PUT /transactions/104788?access_token=e5d48172-92e9-4492-b0af-16d6de8caec1 HTTP/1.1" 200 2 "-" "Synapse/1.32.2"
May 09 08:04:58 sen mx-puppet-discord[982]: May-9 08:04:58.965 [bot-sdk-Appservice] info: Processing transaction 104789
May 09 08:04:58 sen mx-puppet-discord[982]: May-9 08:04:58.966 [bot-sdk-Appservice] info: Processing ephemeral event of type m.typing
May 09 08:04:58 sen mx-puppet-discord[982]: May-9 08:04:58.967 [MatrixEventHandler] info: Got typing event in room !WUPinvICGLJFjKwpsl:monoid.al
May 09 08:04:58 sen mx-puppet-discord[982]: May-9 08:04:58.968 [MatrixEventHandler] error: Error handling appservice ephemeral.event Error: No relay found
May 09 08:04:58 sen mx-puppet-discord[982]:     at NamespaceHandler.<anonymous> (/nix/store/m7ys7454qsvqsxjvfiqpy0sb42256qrp-node_mx-puppet-discord-0.0.0/lib/node_modules/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:709:19)
May 09 08:04:58 sen mx-puppet-discord[982]:     at Generator.next (<anonymous>)
May 09 08:04:58 sen mx-puppet-discord[982]:     at fulfilled (/nix/store/m7ys7454qsvqsxjvfiqpy0sb42256qrp-node_mx-puppet-discord-0.0.0/lib/node_modules/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:17:58)
May 09 08:04:58 sen mx-puppet-discord[982]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 09 08:04:58 sen mx-puppet-discord[982]: 127.0.0.1 - - [09/May/2021:00:04:58 +0000] "PUT /transactions/104789?access_token=e5d48172-92e9-4492-b0af-16d6de8caec1 HTTP/1.1" 200 2 "-" "Synapse/1.32.2"
May 09 08:05:00 sen mx-puppet-discord[982]: May-9 08:05:00.850 [bot-sdk-Appservice] info: Processing transaction 104790
May 09 08:05:00 sen mx-puppet-discord[982]: May-9 08:05:00.851 [bot-sdk-Appservice] info: Processing ephemeral event of type m.typing
May 09 08:05:00 sen mx-puppet-discord[982]: May-9 08:05:00.851 [MatrixEventHandler] info: Got typing event in room !WUPinvICGLJFjKwpsl:monoid.al
May 09 08:05:00 sen mx-puppet-discord[982]: May-9 08:05:00.852 [MatrixEventHandler] error: Error handling appservice ephemeral.event Error: No relay found
May 09 08:05:00 sen mx-puppet-discord[982]:     at NamespaceHandler.<anonymous> (/nix/store/m7ys7454qsvqsxjvfiqpy0sb42256qrp-node_mx-puppet-discord-0.0.0/lib/node_modules/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:709:19)
May 09 08:05:00 sen mx-puppet-discord[982]:     at Generator.next (<anonymous>)
May 09 08:05:00 sen mx-puppet-discord[982]:     at fulfilled (/nix/store/m7ys7454qsvqsxjvfiqpy0sb42256qrp-node_mx-puppet-discord-0.0.0/lib/node_modules/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:17:58)
May 09 08:05:00 sen mx-puppet-discord[982]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 09 08:05:00 sen mx-puppet-discord[982]: 127.0.0.1 - - [09/May/2021:00:05:00 +0000] "PUT /transactions/104790?access_token=e5d48172-92e9-4492-b0af-16d6de8caec1 HTTP/1.1" 200 2 "-" "Synapse/1.32.2"
May 09 08:05:07 sen mx-puppet-discord[982]: May-9 08:05:07.439 [bot-sdk-Appservice] info: Processing transaction 104791
May 09 08:05:07 sen mx-puppet-discord[982]: May-9 08:05:07.440 [bot-sdk-Appservice] info: Processing ephemeral event of type m.typing
May 09 08:05:07 sen mx-puppet-discord[982]: May-9 08:05:07.440 [MatrixEventHandler] info: Got typing event in room !WUPinvICGLJFjKwpsl:monoid.al
May 09 08:05:07 sen mx-puppet-discord[982]: May-9 08:05:07.441 [MatrixEventHandler] error: Error handling appservice ephemeral.event Error: No relay found
May 09 08:05:07 sen mx-puppet-discord[982]:     at NamespaceHandler.<anonymous> (/nix/store/m7ys7454qsvqsxjvfiqpy0sb42256qrp-node_mx-puppet-discord-0.0.0/lib/node_modules/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:709:19)
May 09 08:05:07 sen mx-puppet-discord[982]:     at Generator.next (<anonymous>)
May 09 08:05:07 sen mx-puppet-discord[982]:     at fulfilled (/nix/store/m7ys7454qsvqsxjvfiqpy0sb42256qrp-node_mx-puppet-discord-0.0.0/lib/node_modules/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:17:58)
May 09 08:05:07 sen mx-puppet-discord[982]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 09 08:05:07 sen mx-puppet-discord[982]: 127.0.0.1 - - [09/May/2021:00:05:07 +0000] "PUT /transactions/104791?access_token=e5d48172-92e9-4492-b0af-16d6de8caec1 HTTP/1.1" 200 2 "-" "Synapse/1.32.2"
May 09 08:05:11 sen mx-puppet-discord[982]: May-9 08:05:11.076 [bot-sdk-Appservice] info: Processing transaction 104792
May 09 08:05:11 sen mx-puppet-discord[982]: May-9 08:05:11.077 [bot-sdk-Appservice] info: Processing ephemeral event of type m.typing
May 09 08:05:11 sen mx-puppet-discord[982]: May-9 08:05:11.077 [MatrixEventHandler] info: Got typing event in room !WUPinvICGLJFjKwpsl:monoid.al
May 09 08:05:11 sen mx-puppet-discord[982]: May-9 08:05:11.078 [MatrixEventHandler] error: Error handling appservice ephemeral.event Error: No relay found
May 09 08:05:11 sen mx-puppet-discord[982]:     at NamespaceHandler.<anonymous> (/nix/store/m7ys7454qsvqsxjvfiqpy0sb42256qrp-node_mx-puppet-discord-0.0.0/lib/node_modules/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:709:19)
May 09 08:05:11 sen mx-puppet-discord[982]:     at Generator.next (<anonymous>)
May 09 08:05:11 sen mx-puppet-discord[982]:     at fulfilled (/nix/store/m7ys7454qsvqsxjvfiqpy0sb42256qrp-node_mx-puppet-discord-0.0.0/lib/node_modules/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:17:58)
May 09 08:05:11 sen mx-puppet-discord[982]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 09 08:05:11 sen mx-puppet-discord[982]: 127.0.0.1 - - [09/May/2021:00:05:11 +0000] "PUT /transactions/104792?access_token=e5d48172-92e9-4492-b0af-16d6de8caec1 HTTP/1.1" 200 2 "-" "Synapse/1.32.2"
May 09 08:05:28 sen mx-puppet-discord[982]: May-9 08:05:28.327 [bot-sdk-Appservice] info: Processing transaction 104793
May 09 08:05:28 sen mx-puppet-discord[982]: May-9 08:05:28.328 [bot-sdk-Appservice] info: Processing event of type m.room.message
May 09 08:05:28 sen mx-puppet-discord[982]: May-9 08:05:28.330 [MatrixEventHandler] error: Error handling appservice room.event Error: No relay found
May 09 08:05:28 sen mx-puppet-discord[982]:     at NamespaceHandler.<anonymous> (/nix/store/m7ys7454qsvqsxjvfiqpy0sb42256qrp-node_mx-puppet-discord-0.0.0/lib/node_modules/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:709:19)
May 09 08:05:28 sen mx-puppet-discord[982]:     at Generator.next (<anonymous>)
May 09 08:05:28 sen mx-puppet-discord[982]:     at fulfilled (/nix/store/m7ys7454qsvqsxjvfiqpy0sb42256qrp-node_mx-puppet-discord-0.0.0/lib/node_modules/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:17:58)
May 09 08:05:28 sen mx-puppet-discord[982]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 09 08:05:28 sen mx-puppet-discord[982]: 127.0.0.1 - - [09/May/2021:00:05:28 +0000] "PUT /transactions/104793?access_token=e5d48172-92e9-4492-b0af-16d6de8caec1 HTTP/1.1" 200 2 "-" "Synapse/1.32.2"
May 09 08:05:28 sen mx-puppet-discord[982]: May-9 08:05:28.351 [bot-sdk-Appservice] info: Processing transaction 104794
May 09 08:05:28 sen mx-puppet-discord[982]: May-9 08:05:28.352 [bot-sdk-Appservice] info: Processing ephemeral event of type m.typing
May 09 08:05:28 sen mx-puppet-discord[982]: May-9 08:05:28.352 [MatrixEventHandler] info: Got typing event in room !WUPinvICGLJFjKwpsl:monoid.al
May 09 08:05:28 sen mx-puppet-discord[982]: May-9 08:05:28.357 [MatrixEventHandler] error: Error handling appservice ephemeral.event Error: No relay found
May 09 08:05:28 sen mx-puppet-discord[982]:     at NamespaceHandler.<anonymous> (/nix/store/m7ys7454qsvqsxjvfiqpy0sb42256qrp-node_mx-puppet-discord-0.0.0/lib/node_modules/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:709:19)
May 09 08:05:28 sen mx-puppet-discord[982]:     at Generator.next (<anonymous>)
May 09 08:05:28 sen mx-puppet-discord[982]:     at fulfilled (/nix/store/m7ys7454qsvqsxjvfiqpy0sb42256qrp-node_mx-puppet-discord-0.0.0/lib/node_modules/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:17:58)
May 09 08:05:28 sen mx-puppet-discord[982]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 09 08:05:28 sen mx-puppet-discord[982]: 127.0.0.1 - - [09/May/2021:00:05:28 +0000] "PUT /transactions/104794?access_token=e5d48172-92e9-4492-b0af-16d6de8caec1 HTTP/1.1" 200 2 "-" "Synapse/1.32.2"
May 09 08:05:28 sen systemd[1]: Stopping mx-puppet-discord, a Discord puppeting bridge for Matrix....
May 09 08:05:28 sen systemd[1]: mx-puppet-discord.service: Succeeded.
May 09 08:05:28 sen systemd[1]: Stopped mx-puppet-discord, a Discord puppeting bridge for Matrix..
May 09 08:05:28 sen systemd[1]: mx-puppet-discord.service: Consumed 1.749s CPU time, received 9.2K IP traffic, sent 4.5K IP traffic.
```

**Comment by Sorunome** [comment]
it is actually waiting for synapse to start up

9. 5. 2021 2:40:42 Joe Hermaszewski ***@***.***>:

**Comment by expipiplus1** [comment]
oh weird, not sure what was going on here then...
