### ISSUE TITLE
Unhandled Promise Rejection: TypeError: Cannot read property 'endsWith'

### ISSUE THREAD

**Issue by mpldr** [matrix-discord/mx-puppet-discord#150]
Here is my log:
```
discord-bridge_1    | May-29 18:40:03.264 [Store] info: Starting DB Init
discord-bridge_1    | May-29 18:40:03.268 [Store] info: Filename present in config, using sqlite
discord-bridge_1    | May-29 18:40:03.270 [SQLite3] info: Opening database.db
discord-bridge_1    | May-29 18:40:03.285 [Store] info: Database schema version is 16, latest version is 16
discord-bridge_1    | May-29 18:40:03.290 [Store] info: Starting DB Init
discord-bridge_1    | May-29 18:40:03.292 [Store] info: Database schema version is 4, latest version is 4
discord-bridge_1    | May-29 18:40:03.301 [PuppetBridge] info: Starting application service....
discord-bridge_1    | May-29 18:40:03.320 [PuppetBridge] error: Unhandled Promise Rejection: TypeError: Cannot read property 'endsWith' of undefined
discord-bridge_1    |     at new MatrixClient (/opt/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/MatrixClient.js:79:32)
discord-bridge_1    |     at new Intent (/opt/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Intent.js:44:23)
discord-bridge_1    |     at Appservice.getIntentForUserId (/opt/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Appservice.js:231:22)
discord-bridge_1    |     at Appservice.get botIntent [as botIntent] (/opt/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Appservice.js:132:21)
discord-bridge_1    |     at Appservice.<anonymous> (/opt/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Appservice.js:154:32)
discord-bridge_1    |     at Generator.next (<anonymous>)
discord-bridge_1    |     at /opt/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Appservice.js:8:71
discord-bridge_1    |     at new Promise (<anonymous>)
discord-bridge_1    |     at __awaiter (/opt/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Appservice.js:4:12)
discord-bridge_1    |     at registerBotIntent (/opt/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Appservice.js:152:45)
discord-bridge_1    | May-29 18:40:03.333 [PuppetBridge] error: Promise {
discord-bridge_1    |   <rejected> TypeError: Cannot read property 'endsWith' of undefined
discord-bridge_1    |       at new MatrixClient (/opt/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/MatrixClient.js:79:32)
discord-bridge_1    |       at new Intent (/opt/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Intent.js:44:23)
discord-bridge_1    |       at Appservice.getIntentForUserId (/opt/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Appservice.js:231:22)
discord-bridge_1    |       at Appservice.get botIntent [as botIntent] (/opt/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Appservice.js:132:21)
discord-bridge_1    |       at Appservice.<anonymous> (/opt/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Appservice.js:154:32)
discord-bridge_1    |       at Generator.next (<anonymous>)
discord-bridge_1    |       at /opt/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Appservice.js:8:71
discord-bridge_1    |       at new Promise (<anonymous>)
discord-bridge_1    |       at __awaiter (/opt/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Appservice.js:4:12)
discord-bridge_1    |       at registerBotIntent (/opt/mx-puppet-discord/node_modules/@sorunome/matrix-bot-sdk/lib/appservice/Appservice.js:152:45)
discord-bridge_1    | }
```

Please tell me what else you need. Using the sorunome/mx-puppet-discord Docker Container.

**Comment by aquova** [comment]
I'm seeing the same thing
