### ISSUE TITLE
PostgreSQL Fails On Initialization

### ISSUE THREAD

**Issue by CaptainYukinoshitaHachiman** [matrix-discord/mx-puppet-discord#172]
Here are my outputs and config file.

Mautrix-Telegram bridge works fine using the same database server, while when using mx-puppet-discord it fails no matter when there is no database created, newly created empty database, or one that is migrated from sqlite using `pgloader`.

```yaml
.......
database:
  connString: "postgresql://discord_bridge:PASSWORD@127.0.0.1/discord_bridge"
.......
```

```shell
/etc/mx-puppet-discord $ sudo docker run --restart unless-stopped -v /etc/mx-puppet-discord:/data --network host sorunome/mx-puppet-discord
Sep-11 05:58:24.205 [Store] info: Starting DB Init
Sep-11 05:58:24.209 [Store] info: connString present in config, using postgres
Sep-11 05:58:24.210 [Postgres] info: Opening @127.0.0.1/discord_bridge
Sep-11 05:58:29.244 [Store] warn: Couldn't fetch schema version, defaulting to 0
Sep-11 05:58:29.244 [Store] info: Database schema version is 0, latest version is 16
Sep-11 05:58:29.248 [Store] info: Updating database to v1, "Schema, Userstore, Roomstore"
Sep-11 05:58:34.267 [Store] error: Couldn't update database to schema  1
Sep-11 05:58:34.273 [Store] error: Error: Error creating 'schema': Error: getaddrinfo EAI_AGAIN discord_bridge
    at Store.<anonymous> (/opt/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/store.js:158:23)
    at Generator.throw (<anonymous>)
    at rejected (/opt/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/store.js:18:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Sep-11 05:58:34.274 [Store] error: Schema migration failed! Please visit #mx-puppet-bridge:sorunome.de and ask for help!
Sep-11 05:58:34.275 [Store] info: Rolling back to version  0
Sep-11 05:58:39.291 [Store] error: Error: getaddrinfo EAI_AGAIN discord_bridge
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'discord_bridge'
}
/opt/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/store.js:97
                        throw Error("Failure to update to latest schema. And failed to rollback.");
                              ^

Error: Failure to update to latest schema. And failed to rollback.
    at Store.<anonymous> (/opt/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/store.js:97:31)
    at Generator.throw (<anonymous>)
    at rejected (/opt/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/store.js:18:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

By the way it seems the homeserver of  #mx-puppet-bridge:sorunome.de is down, is it no longer used?

**Comment by dsonck92** [comment]
Tracked by https://gitlab.com/mx-puppet/discord/mx-puppet-discord/-/issues/172
