### ISSUE TITLE
Error creating rooms

### ISSUE THREAD

**Issue by Just-Insane** [matrix-discord/mx-puppet-discord#175]
When trying to create a new room after bridging a guild and opening a room channel, an Internal Server Error is thrown when the bot attempts to create the room:

mx-puppet-discord error logs:
```
Sep 13 10:21:01 matrix.[REMOVED] matrix-mx-puppet-discord[21748]: Sep-13 14:21:01.218 [PuppetBridge] info: Got request to bridge room puppetId=1 roomId=[REMOVED]
Sep 13 10:21:01 matrix.[REMOVED] matrix-mx-puppet-discord[21748]: Sep-13 14:21:01.223 [RoomSync] info: Fetching mxid for roomId [REMOVED] and puppetId -1
Sep 13 10:21:01 matrix.[REMOVED] matrix-mx-puppet-discord[21748]: Sep-13 14:21:01.231 [RoomSync] info: Channel doesn't exist yet, creating entry...
Sep 13 10:21:01 matrix.[REMOVED] matrix-mx-puppet-discord[21748]: Sep-13 14:21:01.232 [NamespaceHandler] info: Fetching new room override data...
Sep 13 10:21:01 matrix.[REMOVED] matrix-mx-puppet-discord[21748]: Sep-13 14:21:01.252 [bot-sdk-MatrixHttpClient] info: (REQ-14) GET http://matrix-nginx-proxy:12080/_matrix/client/r0/account/whoami
Sep 13 10:21:01 matrix.[REMOVED] matrix-mx-puppet-discord[21748]: Sep-13 14:21:01.280 [Util] info: Processing profile update...
Sep 13 10:21:01 matrix.[REMOVED] matrix-mx-puppet-discord[21748]: Sep-13 14:21:01.287 [bot-sdk-MatrixHttpClient] info: (REQ-15) POST http://matrix-nginx-proxy:12080/_matrix/client/r0/createRoom
Sep 13 10:21:01 matrix.[REMOVED] matrix-mx-puppet-discord[21748]: Sep-13 14:21:01.323 [bot-sdk-MatrixLiteClient] error: (REQ-15) {"errcode":"M_UNKNOWN","error":"Internal server error"}
Sep 13 10:21:01 matrix.[REMOVED] matrix-mx-puppet-discord[21748]: Sep-13 14:21:01.324 [RoomSync] error: Error fetching mxid: { errcode: 'M_UNKNOWN', error: 'Internal server error' }
Sep 13 10:21:01 matrix.[REMOVED] matrix-mx-puppet-discord[21748]: Sep-13 14:21:01.326 [MatrixEventHandler] error: Error handling appservice query.room { errcode: 'M_UNKNOWN', error: 'Internal server error' }
```

synapse error logs:
```
Sep 13 10:21:01 matrix.[REMOVED] matrix-synapse[12031]: 2021-09-13 14:21:01,163 - synapse.appservice.api - 120 - WARNING - GET-749 - query_alias to http://matrix-mx-puppet-discord:8432/rooms/%23_discordpuppet__[REMOVED] received 404
```

synapse worker error logs:
```
Sep 13 10:18:50 matrix.[REMOVED] matrix-synapse-worker-generic_worker-18111[12805]: 2021-09-13 14:18:50,319 - shared_secret_authenticator - 54 - INFO - POST-53 - Bad hmac value for user: @bot.matrix-reminder-bot:[REMOVED]
Sep 13 10:20:05 matrix.[REMOVED] matrix-synapse-worker-generic_worker-18111[12805]: 2021-09-13 14:20:05,718 - shared_secret_authenticator - 41 - INFO - POST-642 - Authenticating user: @[REMOVED]:[REMOVED]
Sep 13 10:20:05 matrix.[REMOVED] matrix-synapse-worker-generic_worker-18111[12805]: 2021-09-13 14:20:05,724 - shared_secret_authenticator - 63 - INFO - POST-642 - Authenticated user: @[REMOVED]:[REMOVED]
Sep 13 10:21:01 matrix.[REMOVED] matrix-synapse-worker-generic_worker-18111[12805]: 2021-09-13 14:21:01,315 - synapse.http.server - 93 - ERROR - POST-2296 - Failed handle request via 'RoomCreateRestServlet': <SynapseRequest at 0x7f58830ccb50 method='POST' uri='/_matrix/client/r0/createRoom' clientproto='HTTP/1.0' site=18111>
Sep 13 10:21:01 matrix.[REMOVED] matrix-synapse-worker-generic_worker-18111[12805]: Traceback (most recent call last):
Sep 13 10:21:01 matrix.[REMOVED] matrix-synapse-worker-generic_worker-18111[12805]: File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 258, in _async_render_wrapper
Sep 13 10:21:01 matrix.[REMOVED] matrix-synapse-worker-generic_worker-18111[12805]: callback_return = await self._async_render(request)
Sep 13 10:21:01 matrix.[REMOVED] matrix-synapse-worker-generic_worker-18111[12805]: File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 446, in _async_render
Sep 13 10:21:01 matrix.[REMOVED] matrix-synapse-worker-generic_worker-18111[12805]: callback_return = await raw_callback_return
Sep 13 10:21:01 matrix.[REMOVED] matrix-synapse-worker-generic_worker-18111[12805]: File "/usr/local/lib/python3.8/site-packages/synapse/rest/client/room.py", line 84, in on_POST
Sep 13 10:21:01 matrix.[REMOVED] matrix-synapse-worker-generic_worker-18111[12805]: info, _ = await self._room_creation_handler.create_room(
Sep 13 10:21:01 matrix.[REMOVED] matrix-synapse-worker-generic_worker-18111[12805]: File "/usr/local/lib/python3.8/site-packages/synapse/handlers/room.py", line 726, in create_room
Sep 13 10:21:01 matrix.[REMOVED] matrix-synapse-worker-generic_worker-18111[12805]: await directory_handler.create_association(
Sep 13 10:21:01 matrix.[REMOVED] matrix-synapse-worker-generic_worker-18111[12805]: File "/usr/local/lib/python3.8/site-packages/synapse/handlers/directory.py", line 162, in create_association
Sep 13 10:21:01 matrix.[REMOVED] matrix-synapse-worker-generic_worker-18111[12805]: await self._create_association(room_alias, room_id, servers, creator=user_id)
Sep 13 10:21:01 matrix.[REMOVED] matrix-synapse-worker-generic_worker-18111[12805]: File "/usr/local/lib/python3.8/site-packages/synapse/handlers/directory.py", line 88, in _create_association
Sep 13 10:21:01 matrix.[REMOVED] matrix-synapse-worker-generic_worker-18111[12805]: await self.store.create_room_alias_association(
Sep 13 10:21:01 matrix.[REMOVED] matrix-synapse-worker-generic_worker-18111[12805]: AttributeError: 'GenericWorkerSlavedStore' object has no attribute 'create_room_alias_association'
```

Troubleshooting steps:

1) deleted the mx-puppet-bridge postgres database
2) restarted all services (bot, synapse(+workers))
3) rejoin guilds (works fine)

Next steps: completely remove the bot, including registration and user accounts via synapse-admin

**Comment by Just-Insane** [comment]
After a full reinstall, the same error is still received.

I suspect this may have more to do with using workers than this bot, but I'm not 100% sure.

**Comment by Just-Insane** [comment]
Looks like a bug in synapse: https://github.com/matrix-org/synapse/issues/10716 with a merged PR.
