### ISSUE TITLE
compile failing

### ISSUE THREAD

**Issue by rajil** [matrix-discord/mx-puppet-discord#202]
```
5372 warn mx-puppet-discord@0.0.0 No repository field.
5373 warn mx-puppet-discord@0.0.0 No license field.
5374 verbose stack Error: exited with error code: 128
5374 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/pacote/lib/util/finished.js:12:19)
5374 verbose stack     at ChildProcess.emit (events.js:400:28)
5374 verbose stack     at maybeClose (internal/child_process.js:1058:16)
5374 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
5375 verbose cwd /opt/mx-puppet-discord
5376 verbose Linux 5.15.25-1-lts
5377 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
5378 verbose node v14.19.0
5379 verbose npm  v6.14.16
5380 error Error while executing:
5380 error /usr/bin/git ls-remote -h -t ssh://git@github.com/Sorunome/better-discord.js.git
5380 error
5380 error Host key verification failed.
5380 error fatal: Could not read from remote repository.
5380 error
5380 error Please make sure you have the correct access rights
5380 error and the repository exists.
5380 error
5380 error exited with error code: 128
5381 verbose exit [ 1, true ]
```

**Comment by dsonck92** [comment]
Duplicate of #201
