### ISSUE TITLE
[Error] npm run -> Selfsigned SSL-Certificate maybe a Problem?

### ISSUE THREAD

**Issue by Chiller2019** [matrix-discord/mx-puppet-discord#206]
Hello,

I have a problem with selfsigned certificate. Anyone can help?

Mautrix-Bridges have a easy argument for that like "verify_ssl: false", no problems.

Error:
```
Mar-26 23:19:13.444 [Store] info: Starting DB Init
Mar-26 23:19:13.447 [Store] info: connString present in config, using postgres
Mar-26 23:19:13.448 [Postgres] info: Opening @localhost/discord_db_db?sslmode=disable
Mar-26 23:19:13.583 [Store] info: Database schema version is 16, latest version is 16
Mar-26 23:19:13.588 [Store] info: Starting DB Init
Mar-26 23:19:13.593 [Store] info: Database schema version is 4, latest version is 4
Mar-26 23:19:13.595 [PuppetBridge] info: Starting application service....
Mar-26 23:19:13.603 [bot-sdk-MatrixHttpClient] info: (REQ-1) POST https://matrix.homeserver/_matrix/client/r0/register
Mar-26 23:19:13.666 [bot-sdk-MatrixLiteClient] error: (REQ-1) RequestError: unable to verify the first certificate
    at ClientRequest.<anonymous> (/opt/discord-bridge/node_modules/got/dist/source/core/index.js:962:111)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.origin.emit (/opt/discord-bridge/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  timings: {
    start: 1648333153633,
    socket: 1648333153636,
    lookup: 1648333153638,
    connect: 1648333153648,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1648333153659,
    abort: undefined,
    phases: {
      wait: 3,
      dns: 2,
      tcp: 10,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 26
    }
  }
}
Mar-26 23:19:13.667 [bot-sdk-Appservice] error: Encountered error registering user:
Mar-26 23:19:13.669 [bot-sdk-Appservice] error: RequestError: unable to verify the first certificate
    at ClientRequest.<anonymous> (/opt/discord-bridge/node_modules/got/dist/source/core/index.js:962:111)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.origin.emit (/opt/discord-bridge/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  timings: {
    start: 1648333153633,
    socket: 1648333153636,
    lookup: 1648333153638,
    connect: 1648333153648,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1648333153659,
    abort: undefined,
    phases: {
      wait: 3,
      dns: 2,
      tcp: 10,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 26
    }
  }
}
Mar-26 23:19:13.671 [PuppetBridge] error: Unhandled Promise Rejection: RequestError: unable to verify the first certificate
    at ClientRequest.<anonymous> (/opt/discord-bridge/node_modules/got/dist/source/core/index.js:962:111)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.origin.emit (/opt/discord-bridge/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  timings: {
    start: 1648333153633,
    socket: 1648333153636,
    lookup: 1648333153638,
    connect: 1648333153648,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1648333153659,
    abort: undefined,
    phases: {
      wait: 3,
      dns: 2,
      tcp: 10,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 26
    }
  }
}
Mar-26 23:19:13.672 [PuppetBridge] error: Promise {
  <rejected> RequestError: unable to verify the first certificate
      at ClientRequest.<anonymous> (/opt/discord-bridge/node_modules/got/dist/source/core/index.js:962:111)
      at Object.onceWrapper (events.js:520:26)
      at ClientRequest.emit (events.js:412:35)
      at ClientRequest.origin.emit (/opt/discord-bridge/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
      at TLSSocket.socketErrorListener (_http_client.js:475:9)
      at TLSSocket.emit (events.js:400:28)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)
      at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
      at TLSSocket.emit (events.js:400:28)
      at TLSSocket._finishInit (_tls_wrap.js:937:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12) {
    code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
    timings: {
      start: 1648333153633,
      socket: 1648333153636,
      lookup: 1648333153638,
      connect: 1648333153648,
      secureConnect: undefined,
      upload: undefined,
      response: undefined,
      end: undefined,
      error: 1648333153659,
      abort: undefined,
      phases: [Object]
    }
  }
}
^C

```

**Comment by dsonck92** [comment]
Tracked by https://gitlab.com/mx-puppet/discord/mx-puppet-discord/-/issues/206
