### ISSUE TITLE
webhook messages are not bridged

### ISSUE THREAD

**Issue by lub** [matrix-discord/mx-puppet-discord#37]
It seems the bridge tries to lookup the discord user, which fails (because it is a webhook):

```
Jan-4 18:27:42.894 [DiscordPuppet:Discord] info: Received new message!
Jan-4 18:27:42.923 [UserSync] info: Fetching client for 663084151469244438
Jan-4 18:27:42.926 [UserSync] info: User doesn't exist yet, creating entry...
Jan-4 18:27:43.097 [UserSync] error: Error fetching client: DiscordAPIError: Unknown User
    at /opt/mx-puppet-discord/node_modules/better-discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15
    at /opt/mx-puppet-discord/node_modules/snekfetch/src/index.js:215:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'DiscordAPIError',
  message: 'Unknown User',
  path: '/api/v7/users/663084151469244438',
  code: 10013,
  method: 'GET'
}
Jan-4 18:27:43.097 [DiscordPuppet:Discord] error: Error handling discord message event DiscordAPIError: Unknown User
    at /opt/mx-puppet-discord/node_modules/better-discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15
    at /opt/mx-puppet-discord/node_modules/snekfetch/src/index.js:215:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'DiscordAPIError',
  message: 'Unknown User',
  path: '/api/v7/users/663084151469244438',
  code: 10013,
  method: 'GET'
}
```

**Comment by Sorunome** [comment]
done in https://github.com/matrix-discord/mx-puppet-discord/commit/7807ecd4c1abcf0e1ef5ba8a66b21c87f76fc094

**Comment by lub** [comment]
Cool, it works now. Thank you :)

Does it make sense to think about cleanup? Because you can't sync webhooks via e.g. discord guild membership.

**Comment by Sorunome** [comment]
Maybe auto-part webhook ghosts after a day of inactivity or something?

**Comment by lub** [comment]
Something like that, yes. Although a bigger inactivity timeout (1 week?) makes probably more sense, because I suspect webhooks are also used for pretty irregular things (like blog posts or monitoring alerts)
