### ISSUE TITLE
Incorrect usage of a command produces a traceback in logs

### ISSUE THREAD

**Issue by anoadragon453** [matrix-discord/mx-puppet-discord#38]
No response from the bot and a log error is produced when writing a command incorrectly. For instance, if I write `listguilds` or `unbridgeguild` without anything else, the bridge produces the following error with no feedback for the user:

```
Jan 06 00:55:11 synapse npm[4737]: Jan-6 00:55:11.599 [bot-sdk-Appservice] info: Processing transaction 1732
Jan 06 00:55:11 synapse npm[4737]: Jan-6 00:55:11.600 [bot-sdk-Appservice] info: Processing event of type m.room.message
Jan 06 00:55:11 synapse npm[4737]: 127.0.0.1 - - [05/Jan/2020:23:55:11 +0000] "PUT /transactions/1732?access_token=04a4fa5a-2515-4ffe-9c44-572fa0532daa HTTP/1.1" 200 2 "-" "Synapse/1.7.3"
Jan 06 00:55:11 synapse npm[4737]: Jan-6 00:55:11.616 [BotProvisioner] info: Got message to process with arg=listguilds
Jan 06 00:55:11 synapse npm[4737]: Jan-6 00:55:11.634 [PuppetBridge] error: Error handling appservice room.event error: invalid input syntax for integer: "NaN"
Jan 06 00:55:11 synapse npm[4737]:     at Connection.parseE (/home/synapse/bridges/mx-puppet-discord/node_modules/pg/lib/connection.js:602:11)
Jan 06 00:55:11 synapse npm[4737]:     at Connection.parseMessage (/home/synapse/bridges/mx-puppet-discord/node_modules/pg/lib/connection.js:399:19)
Jan 06 00:55:11 synapse npm[4737]:     at Socket.<anonymous> (/home/synapse/bridges/mx-puppet-discord/node_modules/pg/lib/connection.js:121:22)
Jan 06 00:55:11 synapse npm[4737]:     at Socket.emit (events.js:210:5)
Jan 06 00:55:11 synapse npm[4737]:     at addChunk (_stream_readable.js:309:12)
Jan 06 00:55:11 synapse npm[4737]:     at readableAddChunk (_stream_readable.js:290:11)
Jan 06 00:55:11 synapse npm[4737]:     at Socket.Readable.push (_stream_readable.js:224:10)
Jan 06 00:55:11 synapse npm[4737]:     at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
Jan 06 00:55:11 synapse npm[4737]:   name: 'error',
Jan 06 00:55:11 synapse npm[4737]:   length: 96,
Jan 06 00:55:11 synapse npm[4737]:   severity: 'ERROR',
Jan 06 00:55:11 synapse npm[4737]:   code: '22P02',
Jan 06 00:55:11 synapse npm[4737]:   detail: undefined,
Jan 06 00:55:11 synapse npm[4737]:   hint: undefined,
Jan 06 00:55:11 synapse npm[4737]:   position: '44',
Jan 06 00:55:11 synapse npm[4737]:   internalPosition: undefined,
Jan 06 00:55:11 synapse npm[4737]:   internalQuery: undefined,
Jan 06 00:55:11 synapse npm[4737]:   where: undefined,
Jan 06 00:55:11 synapse npm[4737]:   schema: undefined,
Jan 06 00:55:11 synapse npm[4737]:   table: undefined,
Jan 06 00:55:11 synapse npm[4737]:   column: undefined,
Jan 06 00:55:11 synapse npm[4737]:   dataType: undefined,
Jan 06 00:55:11 synapse npm[4737]:   constraint: undefined,
Jan 06 00:55:11 synapse npm[4737]:   file: 'numutils.c',
Jan 06 00:55:11 synapse npm[4737]:   line: '62',
Jan 06 00:55:11 synapse npm[4737]:   routine: 'pg_atoi'
Jan 06 00:55:11 synapse npm[4737]: }
```

**Comment by Sorunome** [comment]
What did you do to trigger it?

Am 6. Januar 2020 00:57:15 MEZ schrieb Andrew Morgan <notifications@github.com>:

**Comment by Sorunome** [comment]
Ah, right, the syntax is `listGuilds $puppetId`. That it doesn't give the proper error is, indeed, a bug

**Comment by anoadragon453** [comment]
> Ah, right, the syntax is listGuilds $puppetId. That it doesn't give the proper error is, indeed, a bug

Ahh, that's it. Thank you :)

**Comment by anoadragon453** [comment]
Seems to happen with multiple commands. I've updated the issue text.

**Comment by Sorunome** [comment]
Fixed in https://github.com/Sorunome/mx-puppet-bridge/commit/3ed11f63544734f897b2c0049f1b654d722fa849

It'll land in here eventually, didn't deem this change important enough to update this repo ^^
