### ISSUE TITLE
Friend management: removefriend Cannot read property 'id' of null

### ISSUE THREAD

**Issue by anoadragon453** [matrix-discord/mx-puppet-discord#43]
I get the following when sending the bot `removefriend 1 [redacted]#1234`:

```
Jan 13 00:14:43 synapse npm[7713]: Jan-13 00:14:43.196 [BotProvisioner] info: Got message to process with arg=removefriend
Jan 13 00:14:43 synapse npm[7713]: Jan-13 00:14:43.207 [PuppetBridge] error: Error handling appservice room.event TypeError: Cannot read property 'id' of null
Jan 13 00:14:43 synapse npm[7713]:     at RESTMethods.removeFriend (/home/synapse/bridges/mx-puppet-discord/node_modules/better-discord.js/src/client/rest/RESTMethods.js:880:84)
Jan 13 00:14:43 synapse npm[7713]:     at ClientUser.removeFriend (/home/synapse/bridges/mx-puppet-discord/node_modules/better-discord.js/src/structures/ClientUser.js:384:37)
Jan 13 00:14:43 synapse npm[7713]:     at ClientUser.deprecated (internal/util.js:70:15)
Jan 13 00:14:43 synapse npm[7713]:     at DiscordClass.<anonymous> (/home/synapse/bridges/mx-puppet-discord/build/discord.js:946:46)
Jan 13 00:14:43 synapse npm[7713]:     at Generator.next (<anonymous>)
Jan 13 00:14:43 synapse npm[7713]:     at /home/synapse/bridges/mx-puppet-discord/build/discord.js:8:71
Jan 13 00:14:43 synapse npm[7713]:     at new Promise (<anonymous>)
Jan 13 00:14:43 synapse npm[7713]:     at __awaiter (/home/synapse/bridges/mx-puppet-discord/build/discord.js:4:12)
Jan 13 00:14:43 synapse npm[7713]:     at DiscordClass.commandRemoveFriend (/home/synapse/bridges/mx-puppet-discord/build/discord.js:935:16)
Jan 13 00:14:43 synapse npm[7713]:     at BotProvisioner.<anonymous> (/home/synapse/bridges/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/botprovisioner.js:151:59)
Jan 13 00:14:43 synapse npm[7713]:     at Generator.next (<anonymous>)
Jan 13 00:14:43 synapse npm[7713]:     at fulfilled (/home/synapse/bridges/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/botprovisioner.js:5:58)
Jan 13 00:14:43 synapse npm[7713]:     at runMicrotasks (<anonymous>)
Jan 13 00:14:43 synapse npm[7713]:     at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

The friend is not removed, and no response from the bot in the chat.

Guessing just a small bug somewhere :)

**Comment by Sorunome** [comment]
use the uuser id, not the hashtag

Am 13. Januar 2020 00:17:14 MEZ schrieb Andrew Morgan <notifications@github.com>:

**Comment by Sorunome** [comment]
Before you had to user the user id. Now you can also use username#discriminator syntax.

Fixed in https://github.com/matrix-discord/mx-puppet-discord/commit/d438f835aeb9385f5673abdedfce052c4558e665
