### ISSUE TITLE
opens DB twice

### ISSUE THREAD

**Issue by Sorunome** [matrix-discord/mx-puppet-discord#45]
discord also does DB stuffs so it called `store.init` again which results in opening the DB twice

```
Jan 13 16:51:47 sorunome node[17989]: WARNING: Creating a duplicate database object for the same connection.
Jan 13 16:51:47 sorunome node[17989]:     at Postgres.Open (/opt/matrix-appservices/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/db/postgres.js:47:19)
Jan 13 16:51:47 sorunome node[17989]:     at Store.<anonymous> (/opt/matrix-appservices/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/store.js:170:25)
Jan 13 16:51:47 sorunome node[17989]:     at __awaiter (/opt/matrix-appservices/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/store.js:4:12)
Jan 13 16:51:47 sorunome node[17989]:     at Store.openDatabase (/opt/matrix-appservices/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/store.js:160:16)
Jan 13 16:51:47 sorunome node[17989]:     at Store.<anonymous> (/opt/matrix-appservices/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/store.js:45:24)
Jan 13 16:51:47 sorunome node[17989]:     at __awaiter (/opt/matrix-appservices/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/store.js:4:12)
Jan 13 16:51:47 sorunome node[17989]:     at Store.init (/opt/matrix-appservices/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/store.js:43:16)
Jan 13 16:51:47 sorunome node[17989]:     at DiscordStore.<anonymous> (/opt/matrix-appservices/mx-puppet-discord/build/store.js:22:30)
Jan 13 16:51:47 sorunome node[17989]:     at __awaiter (/opt/matrix-appservices/mx-puppet-discord/build/store.js:4:12)
```

**Comment by Sorunome** [comment]
Fixed in https://github.com/matrix-discord/mx-puppet-discord/commit/77ed2177ef0252c0f4bdce5a6141bfeb92600782
