### ISSUE TITLE
npm run start -- -r fails

### ISSUE THREAD

**Issue by WaxyMocha** [matrix-discord/mx-puppet-discord#55]
I'm trying to set up bridge but when I run 

> npm run start -- -r

it fails with:
```
/home/user/synapse/bridges/mx-puppet-discord/node_modules/better-discord.js/src/client/Client.js:40
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/synapse/bridges/mx-puppet-discord/node_modules/better-discord.js/src/index.js:8:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/synapse/bridges/mx-puppet-discord/build/discord.js:25:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

npm ERR! Linux 4.15.0-88-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start" "--" "-r"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! mx-puppet-discord@0.0.0 start: `npm run-script build && node ./build/index.js "-r"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mx-puppet-discord@0.0.0 start script 'npm run-script build && node ./build/index.js "-r"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mx-puppet-discord package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run-script build && node ./build/index.js "-r"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mx-puppet-discord
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mx-puppet-discord
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/synapse/bridges/mx-puppet-discord/npm-debug.log
```

**Comment by Sorunome** [comment]
Node 8 isn't supported, please try with node 10 or newer

Am 24. Februar 2020 13:30:15 MEZ schrieb "Jakub Szymański" <notifications@github.com>:
