### ISSUE TITLE
Bridge Complains / Fails to Forward With Some Unicode Names

### ISSUE THREAD

**Issue by TheDiscordian** [matrix-discord/mx-puppet-discord#71]
The name I know fails is: `. . R̵̩̮͚̤͉͐̓͌̋̑̕͞͡͝ͅu̫̼̲̝̹̩̤̇͌̀̈́͊̓ͅͅṋ̴͓̗̮͔̪̪̫̬̀̑̌͑̒̚͡ͅì̷̢̨̗̫̘̲̯͔́̈́̏̎̂̿͘͠t̢̛͖̮̙̮͕̦̤̀̄̌̀͟ͅĕ̵̛͉̗͕̖̙̘̜͈̮̋͗͐̂͑ͅ . .`. If the message fails due to nickname related reasons, can the bridge fall-back to using the username?

I know some unicode works, for example the nickname `Ðiscordian` works perfectly fine.

Screenshot of the behaviour attached.

![Discord_Doesnt_Forward_Jank_Names](https://user-images.githubusercontent.com/43145244/80654040-6df15680-8a49-11ea-99fa-6a06e23292ca.png)

**Comment by TheDiscordian** [comment]
I captured the exact error, seems the solution is to simply check nickname length, and handle that scenario:

```
Apr-29 19:41:38.958 [DiscordPuppet:MatrixEventHandler] warn: Couldn't send message { DiscordAPIError: Invalid Form Body
username: Must be between 1 and 80 in length.
    at RequestHandler.execute (/var/lib/postgresql/mx-puppet-discord/node_modules/better-discord.js/src/rest/RequestHandler.js:170:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'DiscordAPIError',
  message:
   'Invalid Form Body\nusername: Must be between 1 and 80 in length.',
  method: 'post',
  path:
   '/webhooks/703169301410218117/HczzMdFlEM-hnQodpfk2p-uIMijzX1vU6vtVAJgJEVfYPqQukXnxyXQTXfwlDDlKZfck?wait=true',
  code: 50035,
  httpStatus: 400 }
```
