### ISSUE TITLE
"No relay found" error for a single person's messages Matrix -> Discord

### ISSUE THREAD

**Issue by flukiluke** [matrix-discord/mx-puppet-discord#73]
For whatever reason the bridge decided to stop handling one person's messages this morning from Matrix -> Discord (other bridge users were fine). Each message they sent was accompanied by:
```
May 02 12:26:26 plum bash[21882]: May-2 12:26:26.274 [bot-sdk-Appservice] info: Processing transaction 86317
May 02 12:26:26 plum bash[21882]: May-2 12:26:26.275 [bot-sdk-Appservice] info: Processing event of type m.room.message
May 02 12:26:26 plum bash[21882]: 127.0.0.1 - - [02/May/2020:02:26:26 +0000] "PUT /transactions/86317?access_token=xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx HTTP/1.1" 200 2 "-" "Synapse/1.12.4"
May 02 12:26:26 plum bash[21882]: May-2 12:26:26.288 [MatrixEventHandler] error: Error handling appservice room.event Error: No relay found
May 02 12:26:26 plum bash[21882]:     at NamespaceHandler.<anonymous> (/home/matrix-bridges/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:699:19)
May 02 12:26:26 plum bash[21882]:     at Generator.next (<anonymous>)
May 02 12:26:26 plum bash[21882]:     at fulfilled (/home/matrix-bridges/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:17:58)
May 02 12:26:26 plum bash[21882]:     at runMicrotasks (<anonymous>)
May 02 12:26:26 plum bash[21882]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
in the logs. Note this is all in puppet mode, no relay involved.

I'm not really sure why this occurred, but it would be helpful if this generated an error message into the Matrix chat rather than just failing silently.

Getting the person to do a `relink` fixed the error.

Running commit 227afaf.

**Comment by mirdaki** [comment]
Hey @Sorunome, it looks like I hit this recently too:

```
Mar 13 20:52:06 redacted matrix-mx-puppet-discord[3638532]: Mar-14 04:52:06.333 [bot-sdk-Appservice] info: Processing transaction 1044
Mar 13 20:52:06 redacted matrix-mx-puppet-discord[3638532]: Mar-14 04:52:06.334 [bot-sdk-Appservice] info: Processing event of type m.room.message
Mar 13 20:52:06 redacted matrix-mx-puppet-discord[3638532]: 172.18.0.4 - - [14/Mar/2021:04:52:06 +0000] "PUT /transactions/1044?access_token=1e5986bb-e5cb-5be8-a855-ce24cecc5f2d HTTP/1.1" 200 2 "-" "Synapse/1.29.0"
Mar 13 20:52:06 redacted matrix-mx-puppet-discord[3638532]: Mar-14 04:52:06.369 [MatrixEventHandler] error: Error handling appservice room.event Error: No relay found
Mar 13 20:52:06 redacted matrix-mx-puppet-discord[3638532]:     at NamespaceHandler.<anonymous> (/opt/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:709:19)
Mar 13 20:52:06 redacted matrix-mx-puppet-discord[3638532]:     at Generator.next (<anonymous>)
Mar 13 20:52:06 redacted matrix-mx-puppet-discord[3638532]:     at fulfilled (/opt/mx-puppet-discord/node_modules/mx-puppet-bridge/lib/src/namespacehandler.js:17:58)
Mar 13 20:52:06 redacted matrix-mx-puppet-discord[3638532]:     at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

I get that message whenever I send a puppeted message Matrix -> Discord. I also don't receive messages Discord -> Matrix, nor do I get any log messages to share.

I tried running `relink` as mentioned above, but that does not fix the error. Here are those logs:

```
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]: Mar-14 05:07:46.798 [bot-sdk-Appservice] info: Processing transaction 1046
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]: Mar-14 05:07:46.800 [bot-sdk-Appservice] info: Processing event of type m.room.message
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]: 172.18.0.4 - - [14/Mar/2021:05:07:46 +0000] "PUT /transactions/1046?access_token=1e5986bb-e5cb-5be8-a855-ce24cecc5f2d HTTP/1.1" 200 2 "-" "Synapse/1.29.0"
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]: Mar-14 05:07:46.822 [BotProvisioner] info: Got message to process with arg=relink
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]: Mar-14 05:07:46.825 [MatrixEventHandler] error: Error handling appservice room.event error: invalid input syntax for type integer: "NaN"
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:     at Parser.parseErrorMessage (/opt/mx-puppet-discord/node_modules/pg-protocol/dist/parser.js:278:15)
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:     at Parser.handlePacket (/opt/mx-puppet-discord/node_modules/pg-protocol/dist/parser.js:126:29)
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:     at Parser.parse (/opt/mx-puppet-discord/node_modules/pg-protocol/dist/parser.js:39:38)
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:     at Socket.<anonymous> (/opt/mx-puppet-discord/node_modules/pg-protocol/dist/index.js:10:42)
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:     at Socket.emit (node:events:379:20)
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:     at addChunk (node:internal/streams/readable:313:12)
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:     at readableAddChunk (node:internal/streams/readable:288:9)
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:     at Socket.Readable.push (node:internal/streams/readable:227:10)
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:   length: 108,
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:   severity: 'ERROR',
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:   code: '22P02',
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:   detail: undefined,
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:   hint: undefined,
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:   position: '44',
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:   internalPosition: undefined,
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:   internalQuery: undefined,
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:   where: undefined,
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:   schema: undefined,
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:   table: undefined,
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:   column: undefined,
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:   dataType: undefined,
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:   constraint: undefined,
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:   file: 'numutils.c',
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:   line: '320',
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]:   routine: 'pg_strtoint32'
Mar 13 21:07:46 redacted matrix-mx-puppet-discord[3638532]: }
```

I am using [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy). This issue did occur after I ran an update their, but I didn't see any errors in Ansible, so I'm checking in here first.

Using the `latest` Docker tag. Let me know if I can provide any more info!

**Comment by spantaleev** [comment]
I'm sometimes hitting this "No relay found" error as well. When it happens, messages don't go through in either direction for me.

It seems like the bridge either starts and all is well, or it starts and forever keeps hitting the "No relay found" error.

Seems like the error ultimately comes from here: https://github.com/Sorunome/mx-puppet-bridge/blob/de480828b16090b6335d7b0b855ac12c19bdcc44/src/db/puppetstore.ts#L148-L177

I suppose it's not because the database is unreachable, because.. if I start the bridge with an unreachable database, it does spews some other errors. I don't see such "can't reach database" errors in the logs when I observe that `mx-puppet-discord` is hitting the "No relay found" problem.

------

This makes the bridge quite unreliable. It might take hours/days before you notice that it's not relaying messages in either direction. Worst of all, it happens silently. You don't know that it's failed. It won't tell you that your outgoing (Matrix -> Discord) messages are not delivered either.

-----

It appears that `mx-puppet-discord` and the underlying [mx-puppet-bridge](https://github.com/Sorunome/mx-puppet-bridge) library are not maintained anymore, so we're probably out of luck.
