### ISSUE TITLE
bridge stops working when synapse is unreachable

### ISSUE THREAD

**Issue by lub** [matrix-discord/mx-puppet-discord#74]
It seems when synapse is not reachable at startup the bridge stops briding, although it still answers to e.g. `help`. IMO it'd be better to completely exit (so systemd/docker/... can restart the bridge) or ideally recover gracefully

```
May-3 18:31:25.240 [Store] info: Starting DB Init
    at handleRequest (/opt/mx-puppet-discord/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
May-3 18:31:25.241 [Store] info: connString present in config, using postgres
May-3 18:31:25.241 [Postgres] info: Opening @mx-puppet-discord_postgres/mx-puppet-discord
May-3 18:31:25.263 [Store] info: Database schema version is 14, latest version is 14
May-3 18:31:25.265 [Store] info: Starting DB Init
    at runMicrotasks (<anonymous>)
May-3 18:31:25.269 [Store] info: Database schema version is 4, latest version is 4
May-3 18:31:25.270 [PuppetBridge] info: Starting application service....
May-3 18:31:25.272 [bot-sdk-MatrixLiteClient] info: (REQ-1) POST http://synapse:8008/_matrix/client/r0/register
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
May-3 18:31:25.334 [bot-sdk-MatrixLiteClient] error: (REQ-1) GotError: getaddrinfo ENOTFOUND synapse
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  name: 'RequestError',
  code: 'ENOTFOUND'
}
May-3 18:31:20.840 [PresenceHandler] info: Could not update Matrix presence for @_discordpuppet__159985870458322944:imninja.net GotError: getaddrinfo ENOTFOUND synapse
    at onError (/opt/mx-puppet-discord/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at onError (/opt/mx-puppet-discord/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at handleRequest (/opt/mx-puppet-discord/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
    at handleRequest (/opt/mx-puppet-discord/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
  name: 'RequestError',
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  name: 'RequestError',
  code: 'ENOTFOUND'
  code: 'ENOTFOUND'
}
}
May-3 18:31:25.334 [bot-sdk-Appservice] error: Encountered error registering user:
May-3 18:31:25.334 [bot-sdk-Appservice] error: GotError: getaddrinfo ENOTFOUND synapse
    at onError (/opt/mx-puppet-discord/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at handleRequest (/opt/mx-puppet-discord/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  name: 'RequestError',
  code: 'ENOTFOUND'
}
(node:19) UnhandledPromiseRejectionWarning: GotError: getaddrinfo ENOTFOUND synapse
    at onError (/opt/mx-puppet-discord/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at handleRequest (/opt/mx-puppet-discord/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
May-4 09:07:59.337 [bot-sdk-Appservice] info: Processing transaction 90039
May-4 09:07:59.338 [bot-sdk-Appservice] info: Processing event of type m.room.message
10.0.116.3 - - [04/May/2020:09:07:59 +0000] "PUT /transactions/90039?access_token=e75badd36bd1764bb95697d95657c70d0b6f9adcfbfa975c7e60178e0b6346dd239b40f3b2e2e21ece9fb1d73cb3515c0a9395a3541887b9673501 HTTP/1.1" 200 2 "-" "Synapse/1.12.4"
May-4 09:07:59.380 [BotProvisioner] info: Got message to process with arg=ping
May-4 09:07:59.387 [bot-sdk-MatrixLiteClient] info: (REQ-1) PUT http://synapse:8008/_matrix/client/r0/rooms/!mswbTDsPWEZGxRBSDf%3Aimninja.net/send/m.room.message/1588583279387__REQ0
May-4 09:07:59.843 [bot-sdk-Appservice] info: Processing transaction 90040
May-4 09:07:59.843 [bot-sdk-Appservice] info: Processing event of type m.room.message
10.0.116.3 - - [04/May/2020:09:07:59 +0000] "PUT /transactions/90040?access_token=e75badd36bd1764bb95697d95657c70d0b6f9adcfbfa975c7e60178e0b6346dd239b40f3b2e2e21ece9fb1d73cb3515c0a9395a3541887b9673501 HTTP/1.1" 200 2 "-" "Synapse/1.12.4"
May-4 09:08:02.760 [bot-sdk-Appservice] info: Processing transaction 90041
May-4 09:08:02.760 [bot-sdk-Appservice] info: Processing event of type m.room.message
10.0.116.3 - - [04/May/2020:09:08:02 +0000] "PUT /transactions/90041?access_token=e75badd36bd1764bb95697d95657c70d0b6f9adcfbfa975c7e60178e0b6346dd239b40f3b2e2e21ece9fb1d73cb3515c0a9395a3541887b9673501 HTTP/1.1" 200 2 "-" "Synapse/1.12.4"
May-4 09:08:02.772 [BotProvisioner] info: Got message to process with arg=help
May-4 09:08:02.773 [bot-sdk-MatrixLiteClient] info: (REQ-2) PUT http://synapse:8008/_matrix/client/r0/rooms/!mswbTDsPWEZGxRBSDf%3Aimninja.net/send/m.room.message/1588583282773__REQ1
May-4 09:08:02.983 [bot-sdk-Appservice] info: Processing transaction 90042
May-4 09:08:02.984 [bot-sdk-Appservice] info: Processing event of type m.room.message
10.0.116.3 - - [04/May/2020:09:08:02 +0000] "PUT /transactions/90042?access_token=e75badd36bd1764bb95697d95657c70d0b6f9adcfbfa975c7e60178e0b6346dd239b40f3b2e2e21ece9fb1d73cb3515c0a9395a3541887b9673501 HTTP/1.1" 200 2 "-" "Synapse/1.12.4"
```

**Comment by Sorunome** [comment]
This was actually fixed in the library a few days ago. Pushing the updated package.json here now

**Comment by lub** [comment]
@Sorunome Thanks, thought I'd saw an issue or discussion about this but couldn't find it anymore. Then I'll update later :)
