### ISSUE TITLE
Bridge is trying to send a message to myself?

### ISSUE THREAD

**Issue by AndrewJDR** [matrix-discord/mx-puppet-discord#8]
I suspect that mx-puppet-discord may be trying to create a user for, or in some way send messages to... myself? I'm seeing some errors that look like this send sending an outgoing message from riot into a DM bridge room (or sending an outgoing message from the official discord app into a bridged DM room). This error only occurs when sending an outgoing message, not when receiving an incoming message.
```
Sep-12 08:53:10.570 [DiscordPuppet:Discord] info: Received new message!
Sep-12 08:53:10.572 [UserSync] info: Fetching client for xxxxxxxxxxxxxxxxxxx
Sep-12 08:53:10.573 [ChannelSync] info: Fetching mxid for roomId dm-xxxxxxxxxxxxxxxxxxx and puppetId 1
Sep-12 08:53:10.573 [ChannelSync] info: Channel doesn't exist yet, creating entry...
Sep-12 08:53:10.680 [ChannelSync] error: Error fetching mxid: { DiscordAPIError: Cannot send messages to this user
    at item.request.gen.end (/home/vector/mx-puppet-discord/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
    at then (/home/vector/mx-puppet-discord/node_modules/snekfetch/src/index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'DiscordAPIError',
  message: 'Cannot send messages to this user',
  path: '/api/v7/users/xxxxxxxxxxxxxxxxxxx/channels',
  code: 50007,
  method: 'POST' }
(node:12751) UnhandledPromiseRejectionWarning: DiscordAPIError: Cannot send messages to this user
    at item.request.gen.end (/home/vector/mx-puppet-discord/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
    at then (/home/vector/mx-puppet-discord/node_modules/snekfetch/src/index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:12751) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 60)
```

**Comment by Sorunome** [comment]
Fixed in eb1f581b904b8c6f666bf746647cec5a741dcaf2
