### ISSUE TITLE
Error loading shared library ld-linux-x86-64.so.2: No such file or directory

### ISSUE THREAD

**Issue by Zir0h** [matrix-discord/mx-puppet-discord#94]
Hello,

Using the latest image I got an error on ld.so

```
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /opt/mx-puppet-discord/node_modules/canvas/build/Release/libpixman-1.so.0)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1126:18)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/mx-puppet-discord/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
root@matrix:~# docker images  | grep disco
sorunome/mx-puppet-discord            latest              4649a4f40dd8        17 hours ago        320MB
sorunome/mx-puppet-discord            <none>              a09a0f611d43        2 days ago          219MB
sorunome/mx-puppet-discord            <none>              6dd3f6c96d83        5 weeks ago         219MB
```

Switching back to a09a0f611d43 fixed my issue.
I think it's because the builder image is based on ubuntu and the running container uses alpine.

Rebuilding the image with node:alpine (same image in builder/runner) seems to fix the issue.

**Comment by Zir0h** [comment]
Fixed with 9f26da6
